data = {
    "courseCode":"1-17",
    "description":"测试课程",
    "name":"测试课程",
    "programList":[
        {
            "unitList":[
                {
                    "actionList":[
                        {
                            "actionCode":"action_469",
                            "id":469,
                            "intensityDuration":300,
                            "intensityTimes":25,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=24fffbe4-c3a9-4b37-8724-121beeab05b5.mp4",
                            "name":"myl测试00",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"action_466",
                            "id":466,
                            "intensityDuration":33,
                            "intensityTimes":25,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=3d4a5d04-9202-49c7-8811-aa2e356de487.mp4",
                            "name":"测试测试测试",
                            "part":"胸肩,臀部",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"GBTC0907",
                            "id":462,
                            "intensityDuration":345,
                            "intensityTimes":2,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/06ae5bf6-df5d-492b-a42f-0958892894ed.mp4",
                            "name":"第九套-跳跃运动",
                            "part":"臀部,腿部",
                            "status":0,
                            "type":2
                        }
                    ],
                    "bgMusicUrl":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=5984b400-0ff6-422b-b00f-43a67a7c1dba.mp3",
                    "duration":12,
                    "durationSeconds":736,
                    "id":11,
                    "name":"myl测试单元编码-第一单元",
                    "status":0,
                    "unitCode":"unit_11"
                },
                {
                    "actionList":[
                        {
                            "actionCode":"action_470",
                            "id":470,
                            "intensityDuration":66,
                            "intensityTimes":22,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=5cf22550-680d-40f2-b965-f6bd066e9b61.mp4",
                            "name":"myl测试2",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"action_469",
                            "id":469,
                            "intensityDuration":189,
                            "intensityTimes":25,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=24fffbe4-c3a9-4b37-8724-121beeab05b5.mp4",
                            "name":"myl测试00",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"test1001111",
                            "id":465,
                            "intensityDuration":180,
                            "intensityTimes":18,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/06ae5bf6-df5d-492b-a42f-0958892894ed.mp4",
                            "name":"计时调试",
                            "part":"胸肩,臀部",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"GBTC0907",
                            "id":462,
                            "intensityDuration":90,
                            "intensityTimes":25,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/06ae5bf6-df5d-492b-a42f-0958892894ed.mp4",
                            "name":"第九套-跳跃运动",
                            "part":"臀部,腿部",
                            "status":0,
                            "type":2
                        }
                    ],
                    "bgMusicUrl":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=954ead76-41a3-4887-8241-b27076dc7a5a.mp3",
                    "duration":9,
                    "durationSeconds":580,
                    "id":12,
                    "name":"myl测试单元编码-第二单元",
                    "status":0,
                    "unitCode":"unit_12"
                },
                {
                    "actionList":[
                        {
                            "actionCode":"TUUN2021",
                            "id":414,
                            "intensityDuration":369,
                            "intensityTimes":255,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/1fc80dff-cf25-4ded-9121-a6ac0b9a35ef.mp4",
                            "name":"交替侧后弓步",
                            "part":"胸肩,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"TUUN2020",
                            "id":413,
                            "intensityDuration":123,
                            "intensityTimes":1,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/3b8b1da3-52fa-47fa-b9fb-e7917654537e.mp4",
                            "name":"仰卧高点臀举",
                            "part":"臀部,腿部",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"TUUN1005",
                            "id":410,
                            "intensityDuration":25,
                            "intensityTimes":2,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/9250f60b-b5d1-4680-98a2-a5aad504e172.mp4",
                            "name":"仰卧臀举",
                            "part":"胸肩,腿部",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"SZUR1024",
                            "id":386,
                            "intensityDuration":105,
                            "intensityTimes":3,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/84634cf5-8e9e-483c-a21b-674bf5e39999.mp4",
                            "name":"椅子颈部侧面伸展（右）",
                            "part":"胸肩,腿部",
                            "status":0,
                            "type":1
                        }
                    ],
                    "bgMusicUrl":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=1329448a-8282-458e-bf76-801291547181.mp3",
                    "duration":11,
                    "durationSeconds":682,
                    "id":13,
                    "name":"myl测试单元编码-第三单元",
                    "status":0,
                    "unitCode":"unit_13"
                },
                {
                    "actionList":[
                        {
                            "actionCode":"action_470",
                            "id":470,
                            "intensityDuration":32,
                            "intensityTimes":2,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=5cf22550-680d-40f2-b965-f6bd066e9b61.mp4",
                            "name":"myl测试2",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"action_469",
                            "id":469,
                            "intensityDuration":96,
                            "intensityTimes":23,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=24fffbe4-c3a9-4b37-8724-121beeab05b5.mp4",
                            "name":"myl测试00",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"test1001111",
                            "id":465,
                            "intensityDuration":36,
                            "intensityTimes":21,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/06ae5bf6-df5d-492b-a42f-0958892894ed.mp4",
                            "name":"计时调试",
                            "part":"胸肩,臀部",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"GBTC0907",
                            "id":462,
                            "intensityDuration":99,
                            "intensityTimes":25,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/06ae5bf6-df5d-492b-a42f-0958892894ed.mp4",
                            "name":"第九套-跳跃运动",
                            "part":"臀部,腿部",
                            "status":0,
                            "type":2
                        },
                        {
                            "actionCode":"action_466",
                            "id":466,
                            "intensityDuration":160,
                            "intensityTimes":12,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=3d4a5d04-9202-49c7-8811-aa2e356de487.mp4",
                            "name":"测试测试测试",
                            "part":"胸肩,臀部",
                            "status":0,
                            "type":1
                        }
                    ],
                    "bgMusicUrl":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=80ef41cd-7e3f-4fd8-89fc-fb20c71922f2.mp3",
                    "duration":8,
                    "durationSeconds":483,
                    "id":14,
                    "name":"myl测试单元编码-第四单元",
                    "status":0,
                    "unitCode":"unit_14"
                },
                {
                    "actionList":[
                        {
                            "actionCode":"GBTC0907",
                            "id":462,
                            "intensityDuration":369,
                            "intensityTimes":12,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/06ae5bf6-df5d-492b-a42f-0958892894ed.mp4",
                            "name":"第九套-跳跃运动",
                            "part":"臀部,腿部",
                            "status":0,
                            "type":2
                        },
                        {
                            "actionCode":"GBTC0905",
                            "id":460,
                            "intensityDuration":300,
                            "intensityTimes":25,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/06ae5bf6-df5d-492b-a42f-0958892894ed.mp4",
                            "name":"第九套-体转运动",
                            "part":"手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"action_469",
                            "id":469,
                            "intensityDuration":6,
                            "intensityTimes":1,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=24fffbe4-c3a9-4b37-8724-121beeab05b5.mp4",
                            "name":"myl测试00",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        }
                    ],
                    "bgMusicUrl":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=742c9be7-024a-4a0d-92e7-910ae3ac1522.mp3",
                    "duration":12,
                    "durationSeconds":731,
                    "id":15,
                    "name":"myl测试单元编码-第五单元",
                    "status":0,
                    "unitCode":"unit_15"
                },
                {
                    "actionList":[
                        {
                            "actionCode":"FUUN1023",
                            "id":32,
                            "intensityDuration":23,
                            "intensityTimes":2,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/953632f2-08c9-4321-8759-eda34aa65cb8.mp4",
                            "name":"平板支撑",
                            "part":"胸肩,腿部",
                            "status":0,
                            "type":2
                        },
                        {
                            "actionCode":"action_469",
                            "id":469,
                            "intensityDuration":23,
                            "intensityTimes":3,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=24fffbe4-c3a9-4b37-8724-121beeab05b5.mp4",
                            "name":"myl测试00",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"action_470",
                            "id":470,
                            "intensityDuration":12,
                            "intensityTimes":5,
                            "interVideo":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=5cf22550-680d-40f2-b965-f6bd066e9b61.mp4",
                            "name":"myl测试2",
                            "part":"胸肩,臀部,腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"XUUN1044",
                            "id":444,
                            "intensityDuration":36,
                            "intensityTimes":25,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/f838bc39-06d3-4eaa-9129-2152c8e5c0d9.mp4",
                            "name":"藏腿俯卧撑",
                            "part":"腿部,手臂",
                            "status":0,
                            "type":1
                        },
                        {
                            "actionCode":"XUUN2019",
                            "id":445,
                            "intensityDuration":270,
                            "intensityTimes":25,
                            "interVideo":"https://kuaikuai.oss-cn-beijing.aliyuncs.com/upload/9446e64e-1f43-48f7-8bbd-009507677e7b.mp4",
                            "name":"上斜俯卧撑（椅子）",
                            "part":"腿部,背部",
                            "status":0,
                            "type":1
                        }
                    ],
                    "bgMusicUrl":"https://kifs-test.kuaikuaikeji.com/kifs-gateway-resource/api/resource/GetFile?bucketName=kifs&key=6fccce97-4b54-44a2-87d4-ec9feaf30573.mp3",
                    "duration":7,
                    "durationSeconds":423,
                    "id":16,
                    "name":"myl测试单元编码-第六单元",
                    "status":0,
                    "unitCode":"unit_16"
                }
            ]
        }
    ]
}

# 获取所有 "intensityDuration" 的数值
durations = [action['intensityDuration'] for course in data['programList'] for unit in course['unitList'] for action in unit['actionList']]

# 倒序打印出所有 "intensityDuration" 的数值，并计算总和
durations.reverse()
total = 0
for duration in durations:
    print(duration)
    total += duration

# 打印总和
print('The total sum of intensity duration is:', total)